# Build images on push and pull request
name: build_images
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update

    - name: Build images
      run: |
        cd $GITHUB_WORKSPACE
        scripts/build_images.sh
