# Build images on push and pull request to non-master branches
name: build_images
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build containers
        run: |
          cd $GITHUB_WORKSPACE
          scripts/build_images.sh
