# Build images on push and pull request to non-master branches
name: build_images
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v1

      - name: Build base container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: cerulean_test_docker_images/container-base
          tags: mdstudio/cerulean-test-slurm-base:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
