# Build images and push to Docker Hub on push to the main branch
name: build_push_images
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 0'     # Rebuild every Sunday
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Build containers
        run: |
          cd $GITHUB_WORKSPACE
          scripts/build_images.sh

      - name: Push containers
        run: |
          echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push naturalhpc/cerulean-test-base
          docker push naturalhpc/cerulean-test-base-old
          docker push naturalhpc/cerulean-test-webdav
          docker push naturalhpc/cerulean-test-torque-6
          docker push naturalhpc/cerulean-test-slurm-base
          docker push naturalhpc/cerulean-test-slurm-base-old
          docker push naturalhpc/cerulean-test-slurm-16-05
          docker push naturalhpc/cerulean-test-slurm-17-02
          docker push naturalhpc/cerulean-test-slurm-17-11
          docker push naturalhpc/cerulean-test-slurm-18-08
          docker push naturalhpc/cerulean-test-slurm-19-05
          docker push naturalhpc/cerulean-test-slurm-20-02
          docker push naturalhpc/cerulean-test-slurm-20-11
          docker push naturalhpc/cerulean-test-flaky
