# Build images on push and pull request to non-master branches
name: build_images
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v1

      - name: Build base container
        uses: docker/build-push-action@v2
        with:
          context: cerulean_test_docker_images/container-base
          tags: mdstudio/cerulean-test-base:latest
          load: true

      - name: Build WebDAV container
        uses: docker/build-push-action@v2
        with:
          context: cerulean_test_docker_images/container-webdav
          tags: mdstudio/cerulean-test-webdav:latest

      - name: Build Torque container
        uses: docker/build-push-action@v2
        with:
          context: cerulean_test_docker_images/container-torque
          tags: mdstudio/cerulean-test-torque-6:latest

      - name: Build SLURM base container
        uses: docker/build-push-action@v2
        with:
          context: cerulean_test_docker_images/container-slurm
          file: slurm-base.Dockerfile
          tags: mdstudio/cerulean-test-slurm-base:latest
          load: true
