# Build images on push and pull request to non-master branches
name: build_images
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Build containers
        run: |
          cd $GITHUB_WORKSPACE
          scripts/build_images.sh

      - name: Push containers
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push -a

